### ISSUE TITLE
play2.6 branch example build fails

### ISSUE THREAD

**Issue by lfrost** [iheartradio/play-swagger#162]
I am trying to build the example in the play2.6 branch.  It fails as follows.
```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.iheart#sbt-play-swagger;0.6.1-SNAPSHOT: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]          com.iheart:sbt-play-swagger:0.6.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          com.iheart:sbt-play-swagger:0.6.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13) (/git/play-swagger/example/project/plugins.sbt#L21-22)
[warn]            +- default:example-build:0.1-SNAPSHOT (scalaVersion=2.10, sbtVersion=0.13)
sbt.ResolveException: unresolved dependency: com.iheart#sbt-play-swagger;0.6.1-SNAPSHOT: not found
```

**Comment by kailuowang** [comment]
i just corrected the version in that branch, do you want to pull the latest code and try again?

**Comment by lfrost** [comment]
It is still not finding play-swagger.  Is an additional repository resolver needed in build.sbt?
```
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scalatestplus.play#scalatestplus-play_2.12;1.5.1: not found
[warn]  :: com.iheart#play-swagger_2.12;0.6.1-PLAY2.6-M5: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]          org.scalatestplus.play:scalatestplus-play_2.12:1.5.1 (/git/play-swagger/example/build.sbt#L9-16)
[warn]            +- example:example_2.12:1.0-SNAPSHOT
[warn]          com.iheart:play-swagger_2.12:0.6.1-PLAY2.6-M5 ((com.iheart.sbtPlaySwagger.SwaggerPlugin) SwaggerPlugin.scala#L28)
[warn]            +- example:example_2.12:1.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: org.scalatestplus.play#scalatestplus-play_2.12;1.5.1: not found
unresolved dependency: com.iheart#play-swagger_2.12;0.6.1-PLAY2.6-M5: not found
```
It is also not finding scalatestplus-play now.  I think you need a newer version for Scala 2.12.  The following changes fixed the scalatestplus-play problem, removed a warning about cache, and gets the latest version of swagger-ui.

```
diff --git a/example/build.sbt b/example/build.sbt
index eeebe31..81d74e2 100644
--- a/example/build.sbt
+++ b/example/build.sbt
@@ -8,10 +8,10 @@ scalaVersion := "2.12.2"
 
 libraryDependencies ++= Seq(
   jdbc,
-  cache,
+  cacheApi,
   ws,
-  "org.scalatestplus.play" %% "scalatestplus-play" % "1.5.1" % Test,
-  "org.webjars" % "swagger-ui" % "2.2.0"  //play-swagger ui integration
+  "org.scalatestplus.play" %% "scalatestplus-play" % "3.0.0-M3" % "test",
+  "org.webjars"            %  "swagger-ui"         % "3.0.8"
 )
 
 swaggerDomainNameSpaces := Seq("models")
```

**Comment by lfrost** [comment]
Is there any update on this?  The example still does not work for me.

**Comment by kailuowang** [comment]
for some reason the sbt plugin might not sync to the sbt plugin bintray repo, you might need to add 
`resolvers += Resolver. bintrayRepo("iheartradio", "maven") ` to your `plugins.sbt`. Also the latest release is `play2.6-RC2`.

**Comment by lfrost** [comment]
That did not work.  With or without the explicit resolver, it looks for
  https://jcenter.bintray.com/com/iheart/play-swagger_2.12/0.6.1-PLAY2.6-RC2/play-swagger_2.12-0.6.1-PLAY2.6-RC2.pom
but that does not exist.  There is no play-swagger_2.12 directory at all on bintray, only play-swagger_2.11.

**Comment by kailuowang** [comment]
Looks like you are using the lib jar rather than the sbt plugin?

**Comment by lfrost** [comment]
No, I am trying to build your example program, which uses the SBT plugin.  Details below.

$ git branch
  master
* play2.6
$ git log | head -n1
commit 880174282a5c0bd753554c7b490f83240bda29c0
$ git diff project/plugins.sbt
diff --git a/example/project/plugins.sbt b/example/project/plugins.sbt
index 1927779..777945f 100644
--- a/example/project/plugins.sbt
+++ b/example/project/plugins.sbt
@@ -1,3 +1,5 @@
+resolvers += Resolver.bintrayRepo("iheartradio", "maven")
+
 // The Play plugin
 addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.6.0-M5")
 
@@ -18,6 +20,6 @@ addSbtPlugin("com.typesafe.sbt" % "sbt-mocha" % "1.1.0")
 addSbtPlugin("org.irundaia.sbt" % "sbt-sassify" % "1.4.2")
 
 // play swagger plugin
-addSbtPlugin("com.iheart" % "sbt-play-swagger" % "0.6.1-PLAY2.6-M5")
+addSbtPlugin("com.iheart" % "sbt-play-swagger" % "0.6.1-PLAY2.6-RC2")
 
 
$ sbt compile
[warn] Executing in batch mode.
[info] Resolving org.scalatestplus.play#scalatestplus-play_2.12;1.5.1 ...
[warn]  module not found: org.scalatestplus.play#scalatestplus-play_2.12;1.5.1
[warn] ==== local: tried
[warn]   $HOME/.ivy2/local/org.scalatestplus.play/scalatestplus-play_2.12/1.5.1/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/org/scalatestplus/play/scalatestplus-play_2.12/1.5.1/scalatestplus-play_2.12-1.5.1.pom
[warn] ==== activator-local: tried
[warn]   /opt/activator-dist-1.3.12/repository/org.scalatestplus.play/scalatestplus-play_2.12/1.5.1/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   $HOME/.activator/repository/org.scalatestplus.play/scalatestplus-play_2.12/1.5.1/ivys/ivy.xml
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/org/scalatestplus/play/scalatestplus-play_2.12/1.5.1/scalatestplus-play_2.12-1.5.1.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/org.scalatestplus.play/scalatestplus-play_2.12/1.5.1/ivys/ivy.xml
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/org/scalatestplus/play/scalatestplus-play_2.12/1.5.1/scalatestplus-play_2.12-1.5.1.pom
[info] Resolving com.iheart#play-swagger_2.12;0.6.1-PLAY2.6-RC2 ...
[warn]  module not found: com.iheart#play-swagger_2.12;0.6.1-PLAY2.6-RC2
[warn] ==== local: tried
[warn]   $HOME/.ivy2/local/com.iheart/play-swagger_2.12/0.6.1-PLAY2.6-RC2/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/iheart/play-swagger_2.12/0.6.1-PLAY2.6-RC2/play-swagger_2.12-0.6.1-PLAY2.6-RC2.pom
[warn] ==== activator-local: tried
[warn]   /opt/activator-dist-1.3.12/repository/com.iheart/play-swagger_2.12/0.6.1-PLAY2.6-RC2/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   $HOME/.activator/repository/com.iheart/play-swagger_2.12/0.6.1-PLAY2.6-RC2/ivys/ivy.xml
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/iheart/play-swagger_2.12/0.6.1-PLAY2.6-RC2/play-swagger_2.12-0.6.1-PLAY2.6-RC2.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.iheart/play-swagger_2.12/0.6.1-PLAY2.6-RC2/ivys/ivy.xml
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/com/iheart/play-swagger_2.12/0.6.1-PLAY2.6-RC2/play-swagger_2.12-0.6.1-PLAY2.6-RC2.pom
[info] Resolving jline#jline;2.14.3 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: org.scalatestplus.play#scalatestplus-play_2.12;1.5.1: not found
[warn]  :: com.iheart#play-swagger_2.12;0.6.1-PLAY2.6-RC2: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::

**Comment by wwbakker** [comment]
@lfrost with this merge request ( #167 ) merged, it should be fixed now.

**Comment by lfrost** [comment]
Still the same error.  Look at https://jcenter.bintray.com/com/iheart/.  There is no 2.12 directory.

```
$ git branch
  master
* play2.6
$ git log | head -n1
commit fd360467a3b3453c7a695d85759d057fe1d82c25
$ sbt compile
[warn] Executing in batch mode.
[warn]   For better performance, hit [ENTER] to switch to interactive mode, or
[warn]   consider launching sbt without any commands, or explicitly passing 'shell'
[info] Loading global plugins from $HOME/.sbt/0.13/plugins
[info] Loading project definition from $HOME/tmp/git/new/play-swagger/example/project
[info] Set current project to example (in build file:$HOME/tmp/git/new/play-swagger/example/)
[info] Updating {file:$HOME/tmp/git/new/play-swagger/example/}root...
[info] Resolving com.iheart#play-swagger_2.12;0.6.1-PLAY2.6 ...
[warn]  module not found: com.iheart#play-swagger_2.12;0.6.1-PLAY2.6
[warn] ==== local: tried
[warn]   $HOME/.ivy2/local/com.iheart/play-swagger_2.12/0.6.1-PLAY2.6/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/iheart/play-swagger_2.12/0.6.1-PLAY2.6/play-swagger_2.12-0.6.1-PLAY2.6.pom
[warn] ==== activator-local: tried
[warn]   /opt/activator-dist-1.3.12/repository/com.iheart/play-swagger_2.12/0.6.1-PLAY2.6/ivys/ivy.xml
[warn] ==== activator-launcher-local: tried
[warn]   $HOME/.activator/repository/com.iheart/play-swagger_2.12/0.6.1-PLAY2.6/ivys/ivy.xml
[warn] ==== typesafe-releases: tried
[warn]   http://repo.typesafe.com/typesafe/releases/com/iheart/play-swagger_2.12/0.6.1-PLAY2.6/play-swagger_2.12-0.6.1-PLAY2.6.pom
[warn] ==== typesafe-ivy-releasez: tried
[warn]   http://repo.typesafe.com/typesafe/ivy-releases/com.iheart/play-swagger_2.12/0.6.1-PLAY2.6/ivys/ivy.xml
[warn] ==== jcenter: tried
[warn]   https://jcenter.bintray.com/com/iheart/play-swagger_2.12/0.6.1-PLAY2.6/play-swagger_2.12-0.6.1-PLAY2.6.pom
[info] Resolving jline#jline;2.14.3 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.iheart#play-swagger_2.12;0.6.1-PLAY2.6: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]          com.iheart:play-swagger_2.12:0.6.1-PLAY2.6 ((com.iheart.sbtPlaySwagger.SwaggerPlugin) SwaggerPlugin.scala#L28)
[warn]            +- example:example_2.12:1.0-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.iheart#play-swagger_2.12;0.6.1-PLAY2.6: not found
```

**Comment by wwbakker** [comment]
@kailuowang Did you say you released it?

**Comment by kailuowang** [comment]
It's here https://bintray.com/iheartradio/maven/play-swagger/0.6.1-PLAY2.6
maybe for some reason it's not synced to bintray jcenter?
try add 
```
resolvers += Resolver.bintrayRepo("iheartradio", "maven")
```

**Comment by cjwebb** [comment]
Adding a resolver fixes the example in the branch.
Do you have any idea why it no longer syncs to the default location (so that it works without adding the Resolver)?

**Comment by kailuowang** [comment]
@cjwebb could some glitch on bintray in regards to scala 2.12 artifacts.

**Comment by kailuowang** [comment]
It should be fixed by bintray now

**Comment by cjwebb** [comment]
Excellent, thanks very much! Can confirm its working for me.
Did you get in contact with bintray, or did it just start working again?

**Comment by kailuowang** [comment]
Thanks for confirming! I contacted bintray, who fixed the link. Closing now.

**Comment by mikeumus** [comment]
Putting the path in `~/.sbt/repositories` that had a version for Scala 2.10 that worked with my sbt 0.13 worked for me:

```
[repositories]
local
iheart-sbt-plugin-releases: https://dl.bintray.com/iheartradio/sbt-plugins, [organization]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[type]s/[artifact](-[classifier] ).[ext]
iheart-play-swagger_2.11-releases: https://jcenter.bintray.com
```

and the `jcenter` version for `sbt publishLocal`
